# Generated by Django 4.2.28 on 2026-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ternak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ternak', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umur', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ternak/')),
                ('status_ternak', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipesan', 'Dipesan'), ('Terjual', 'Terjual')], default='Tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ternak',
                'ordering': ['-created_at'],
            },
        ),
    ]
