# Generated by Django 4.2.28 on 2026-03-10 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ternak',
            name='umur',
        ),
        migrations.AddField(
            model_name='ternak',
            name='berat_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ternak',
            name='jenis',
            field=models.CharField(default='Sapi', max_length=100),
        ),
        migrations.AddField(
            model_name='ternak',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ternak',
            name='tanggal_penimbangan',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
