# Generated by Django 4.2.28 on 2026-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_remove_ternak_umur_ternak_berat_target_ternak_jenis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_daging', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('bagian', models.CharField(max_length=100)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='daging/')),
                ('status_daging', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terjual', 'Terjual'), ('Pre Order', 'Pre Order')], default='Tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daging',
                'ordering': ['-created_at'],
            },
        ),
    ]
