# Generated by Django 6.0.3 on 2026-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_daging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invest', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umur', models.IntegerField()),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=15)),
                ('harga_jual_per_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deskripsi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='invest/')),
                ('status_investernak', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipesan', 'Dipesan'), ('Terjual', 'Terjual')], default='Tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invest',
                'ordering': ['-created_at'],
            },
        ),
    ]
