# Generated by Django 4.2.28 on 2026-03-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_invest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='jenis',
            field=models.CharField(default='Sapi', max_length=100),
        ),
    ]
