# Generated by Django 4.2.28 on 2026-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_invest_jenis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invest',
            old_name='harga_beli',
            new_name='harga_sapi',
        ),
        migrations.RenameField(
            model_name='invest',
            old_name='nama',
            new_name='nama_paket',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='harga_jual_per_kg',
        ),
        migrations.RemoveField(
            model_name='invest',
            name='umur',
        ),
        migrations.AddField(
            model_name='invest',
            name='biaya_pemeliharaan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invest',
            name='durasi_hari',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='invest',
            name='fee_marketing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invest',
            name='harga_jual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invest',
            name='hasil_investor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invest',
            name='keuntungan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invest',
            name='roi_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invest',
            name='total_modal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invest',
            name='vaksin_vitamin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ternak',
            name='kelas',
            field=models.CharField(blank=True, choices=[('A', 'Kelas A'), ('B', 'Kelas B'), ('C', 'Kelas C'), ('D', 'Kelas D'), ('E', 'Kelas E'), ('Patungan', 'Patungan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invest',
            name='berat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invest',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invest',
            name='status_investernak',
            field=models.CharField(choices=[('Open', 'Open'), ('Ongoing', 'Ongoing'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='jenis',
            field=models.CharField(choices=[('Sapi', 'Sapi'), ('Kambing', 'Kambing')], default='Sapi', max_length=100),
        ),
    ]
