# Generated by Django 4.2.28 on 2026-03-18 14:27

import catalogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_rename_harga_beli_invest_harga_sapi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daging',
            name='id_daging',
            field=models.CharField(default=catalogs.models.generate_daging_id, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invest',
            name='id_invest',
            field=models.CharField(default=catalogs.models.generate_invest_id, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='id_ternak',
            field=models.CharField(default=catalogs.models.generate_ternak_id, editable=False, max_length=50, unique=True),
        ),
    ]
