# Generated by Django 4.2.28 on 2026-03-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_daging_id_daging_alter_invest_id_invest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternak',
            name='tanggal_penimbangan',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
