# Generated by Django 4.2.28 on 2026-05-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_fix_tanggal_penimbangan_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternak',
            name='status_ternak',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Sold', 'Sold')], default='Available', max_length=20),
        ),
    ]
