# Generated by Django 4.2.28 on 2026-05-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_alter_ternak_status_ternak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternak',
            name='jenis',
            field=models.CharField(default='Sapi', max_length=100),
        ),
    ]
