# Generated by Django 4.2.28 on 2026-05-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_alter_ternak_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternak',
            name='status_ternak',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Sold', 'Sold')], default='Available', max_length=20),
        ),
    ]
