# Generated by Django 4.2.28 on 2026-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_alter_ternak_status_ternak'),
    ]

    operations = [
        migrations.AddField(
            model_name='daging',
            name='harga_modal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ternak',
            name='harga_modal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
