# Generated by Django 4.2.28 on 2026-05-28 22:46
# Modified: wrapped in SeparateDatabaseAndState because the indexes already
# exist in the remote DB (from a rolled-back migration). Django will update
# its internal model state without issuing any DDL statements.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0012_daging_harga_modal_ternak_harga_modal'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # database_operations is empty — indexes already exist in the DB
            database_operations=[],
            # state_operations tell Django the fields now have db_index=True
            state_operations=[
                migrations.AlterField(
                    model_name='daging',
                    name='bagian',
                    field=models.CharField(db_index=True, max_length=100),
                ),
                migrations.AlterField(
                    model_name='daging',
                    name='harga_per_kg',
                    field=models.DecimalField(db_index=True, decimal_places=2, max_digits=15),
                ),
                migrations.AlterField(
                    model_name='daging',
                    name='status_daging',
                    field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terjual', 'Terjual'), ('Pre Order', 'Pre Order')], db_index=True, default='Tersedia', max_length=20),
                ),
                migrations.AlterField(
                    model_name='ternak',
                    name='berat',
                    field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                migrations.AlterField(
                    model_name='ternak',
                    name='harga',
                    field=models.DecimalField(db_index=True, decimal_places=2, max_digits=15),
                ),
                migrations.AlterField(
                    model_name='ternak',
                    name='jenis',
                    field=models.CharField(db_index=True, default='Sapi', max_length=100),
                ),
                migrations.AlterField(
                    model_name='ternak',
                    name='status_ternak',
                    field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Sold', 'Sold')], db_index=True, default='Available', max_length=20),
                ),
            ],
        ),
    ]
