# Generated by Django 4.2.28 on 2026-05-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daging',
            name='bagian',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='daging',
            name='harga_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='daging',
            name='status_daging',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Terjual', 'Terjual'), ('Pre Order', 'Pre Order')], default='Tersedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='berat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='jenis',
            field=models.CharField(default='Sapi', max_length=100),
        ),
        migrations.AlterField(
            model_name='ternak',
            name='status_ternak',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Sold', 'Sold')], default='Available', max_length=20),
        ),
    ]
