# Generated by Django 4.2.28 on 2026-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_resetpasswordotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordotp',
            name='otp',
            field=models.CharField(max_length=100),
        ),
    ]
