# Generated by Django 4.2.28 on 2026-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_resetpasswordotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('CEO', 'CEO'), ('Komisaris', 'Komisaris'), ('Customer', 'Customer')], default='Customer', max_length=50),
        ),
    ]
