# Generated by Django 4.2.28 on 2026-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='akses_investernak',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='akses_mazdafarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='akses_mazdaging',
            field=models.BooleanField(default=True),
        ),
    ]
