# Generated by Django 4.2.28 on 2026-04-13 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0008_fix_tanggal_penimbangan_default'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesananDaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pesanan', models.CharField(choices=[('Diproses', 'Diproses'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Diproses', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_daging_customer', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan_daging_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pesanan_daging',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranDaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagihan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('menunggu_persetujuan', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sudah_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='sales.pesanandaging')),
            ],
            options={
                'db_table': 'pembayaran_daging',
            },
        ),
        migrations.CreateModel(
            name='OrderItemDaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_pesanan_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.daging')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.pesanandaging')),
            ],
            options={
                'db_table': 'order_item_daging',
            },
        ),
    ]
