# Generated by Django 4.2.28 on 2026-04-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0003_add_pesanan_invest_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nominal_pembayaran', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_pengirim', models.CharField(max_length=100)),
                ('nomor_rekening_pengirim', models.CharField(max_length=50)),
                ('tanggal_transfer', models.DateField()),
                ('waktu_transfer', models.TimeField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Menunggu Verifikasi', 'Menunggu Verifikasi'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Menunggu Verifikasi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('catatan_verifikasi', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_created', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'riwayat_pembayaran',
                'ordering': ['-created_at'],
            },
        ),
    ]
