# Generated by Django 4.2.28 on 2026-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_riwayatpembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpembayaran',
            name='nama_pengirim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
