# Generated by Django 4.2.28 on 2026-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_riwayatpembayaran_nama_pengirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpembayaran',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
