# Generated by Django 4.2.28 on 2026-05-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_riwayatpembayaran_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanInvestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_jual_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('harga_jual_aktual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('biaya_pakan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('biaya_operasional', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('biaya_obat_vitamin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fee_marketing', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('laba_kotor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('laba_bersih', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bagi_hasil_investor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='sales.pesananinvest')),
            ],
            options={
                'db_table': 'laporan_investasi',
            },
        ),
        migrations.CreateModel(
            name='HistoriBerat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_input', models.DateField()),
                ('berat_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('estimasi_harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histori_berat', to='sales.laporaninvestasi')),
            ],
            options={
                'db_table': 'histori_berat',
                'ordering': ['tanggal_input'],
            },
        ),
    ]
