# Generated by Django 4.2.28 on 2026-05-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_laporaninvestasi_historiberat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='status_pesanan',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesanandaging',
            name='status_pesanan',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesananinvest',
            name='status_pesanan',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='riwayatpembayaran',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Menunggu Verifikasi', max_length=50),
        ),
    ]
