# Generated by Django 4.2.28 on 2026-05-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_pesanan_status_pesanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='status_pesanan',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processed', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesanandaging',
            name='status_pesanan',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processed', max_length=20),
        ),
        migrations.AlterField(
            model_name='pesananinvest',
            name='status_pesanan',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processed', max_length=20),
        ),
    ]
