# Generated by Django 4.2.28 on 2026-05-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_pesanan_status_pesanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporaninvestasi',
            name='target_berat_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
