# Generated by Django 4.2.28 on 2026-05-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_laporaninvestasi_target_berat_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='ongkir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pesanandaging',
            name='ongkir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
