# Generated by Django 4.2.28 on 2026-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_pesanan_ongkir_pesanandaging_ongkir'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiberat',
            name='harga_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='laporaninvestasi',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
