# Generated by Django 4.2.28 on 2026-05-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_historiberat_harga_per_kg_laporaninvestasi_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpembayaran',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
